server{
    listen 8081 ssl;
    server_name localhost;
    root /wwwroot/phpMyAdmin;
    index index.php index.html;

    location ~ [^/]\.php(/|$){
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php83:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /tmp/ {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
        expires      30d;
    }

    location ~ .*\.(js|css)?$ {
        expires      12h;
    }

    location ~ /\. {
        deny all;
    }

    access_log  /var/log/nginx/phpMyAdmin.access.log main;
}
